### ISSUE TITLE
Synapse download

### ISSUE THREAD

**Issue by Ian2696** [skannan4/cm-entropy-score#1]
Hi 

I can't seem to access your synapse download page. A message appears saying 'you are not authorised to access the page requested'. Would it be possible for this to be made accessible? I have made a synapse account. 

Thanks 
Ian

**Comment by skannan4** [comment]
Hey Ian - my mistake, I think I forgot to mark it public. I've done so now. Can you confirm that you can access the files?

**Comment by Ian2696** [comment]
Hi
I can now access the files. Thanks for your help. 
Ian
